contributors/ojokne.html
=> Add ojokne contributor card

README.md
=> Add Uganda flag

contributors/devabdulsalam.html
=> add devabdulsalam contributor card

contributors/Mercy435.html
=> Add Mercy435 contributor card

contributors/650DataNerd.html
=> Add 650DataNerd contributor card

contributors/busayo-OD.html
=> Add busayo-OD contributor card

contributors/richieoscar.html
=> feat: Add Card to Contributors list

contributors/adewaleijalana.html
=> Add adewaleijalana contributor card

contributors/Muniru0.html
The scripts/contributors.js does not exists by default so I had to create it before it worked. I have pushed it alongside my code just incase I missed something or I pulled the wrong branch or something other than an error that made sure that it wasn't included from the branch I cloned.
=> chore: add Muniru0.html to /contributors

contributors/heyolaniran.html
=> feat: adding my contibutor profile

contributors/frankchinedu.html
=> Add frankchinedu contributor card

contributors/OShuaib.html
- [*] I had fun going through this tutorial (ノ^o^)ノ and learned on the way ٩(＾◡＾)۶
=> add OShuaib contributor card

contributors/zealsham.html
=> zealsham card

contributors/casperdkk.html
=> Add CasperDkk contributor card

contributors/Cyber-Lord.html
The tutorial isnt currently in sync at the moment with the files. In the scripts, it's only load-card.js that is available not the contributors.js
=> Add Umar Adamu to contributors list

README.md, contributors/AlphonseMehounme.html
=> Add AlphonseMehounme contributor card and Benin Flag

contributors/codaMW.html
=> Add codaMW contributor card

contributors/casperdkk.html
=> Add CasperDkk contributor card with flag

README.md, contributors/yhzlsm.html
=> Add yhzlsm contributor card and flag

contributors/AdamuAbba.html
=> Add AdamuAbba contributor card

contributors/Muniru0.html
=> chore: add Ghana Flag to new PR

contributors/ogedengbewisdom.html
=> add ogedengbewisdom contributor card

contributors/amosoo7.html
=> Add amosoo7 contributor card

contributors/codaMW.html
[Before](url
) submitting this pull request, please go through the checklist below.
=> Added a flag to my name

README.md, contributors/mary.html
=> Add Zeegaths contributor card

contributors/Sammie05.html
=> Sammie05 contributor card
